server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4040/realms/myrealm

management:
  endpoints:
    web:
      exposure:
        include: info,health