server:
  port: 8092

spring:
  security:
    oauth2:
      client:
        registration:
          grp_read_svc:
            provider: myrealm
            client-id: grp_read_svc
            client-secret: L9ubOmq5IXzGcemlh8IOblRjPe8yKklX
            authorization-grant-type: client_credentials
            scope: grp-read-only-svc
        provider:
          uaa:
            authorization-uri: http://localhost:4040/realms/myrealm/protocol/openid-connect/auth
            token-uri: http://localhost:4040/realms/myrealm/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4040/realms/myrealm

resources:
  base-uri: http://localhost:8082
